### ISSUE TITLE
Create RefApps

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/SDS-Framework#115]
Create an `Examples` directory with RefApps similar to https://github.com/ARM-software/MDK-Middleware/tree/main/Examples

It should contain:
- FileSystem\SDS_FileSystem.csolution.yml
- Network\SDS_Network.csolution.yml
- USB\SDS_USB.csolution.yml

Each csolution.yml contains two projects:
- DataTest.cproject.yml  - verifies correct communication. Configure bandwidth to reflect application requirements
- AlgorithmTest.cproject.yml - template for verifying user algorithm

Each csolution.yml contains two target-types:
```yml
  target-types:
    - type:                               # this should be inserted by VS Code, most likely it does not work this way yet
    #   board: <board_name>
    #   variables:
    #     - Board-Layer: <board_layer>.clayer.yml
    
    - type: AVH-SSE-300       # simulator target
      board: ARM::V2M-MPS3-SSE-300-FVP
      device: ARM::SSE-300-MPS3
      define:
        - SIMULATOR
```

Each csolution.yml contains four build-types:

```yml
  build-types:
    - type: DebugRec
    - type: DebugPlay
    - type: ReleaseRec
      define:
        - PLAY
    - type: ReleasePlay
      define:
        - PLAY
```

Register these examples in PDSC with:
```
  <examples>
    <example name="SDS_FileSystem" doc="File_Demo/README.md" folder="Examples/FileSystem">
      <description>Data streaming for DSP/ML algorithm testing using File System in target</description>
      <project>
        <environment name="csolution" load="SDS_FileSystem.csolution.yml"/>
      </project>
    </example>
    <example name="SDS_Network" doc="README.md" folder="Examples/Network">
      <description>Data streaming for DSP/ML algorithm testing using Ethernet connection to Host</description>
      <project>
        <environment name="csolution" load="SDS_Network.csolution.yml"/>
      </project>
    </example>
    <example name="SDS_USB" doc="README.md" folder="Examples/USB">
      <description>Data streaming for DSP/ML algorithm testing using USB Device connection to Host</description>
      <project>
        <environment name="csolution" load="USB_Device.csolution.yml"/>
      </project>
    </example>
  </examples>
```

As the projects are highly identical, they may be in a common directory for development and copied during the pack build process. In this case there should be a batch file to allow working with local repo flow and clear documentation.
