### ISSUE TITLE
Consider to add a `header:` in addition to `content:` in schema

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/SDS-Framework#59]
To capture a header before a data stream that is repeated consider to add `header:` to the schema.
https://github.com/ARM-software/SDS-Framework/tree/main/schema

Example:

```
struct { 
  uint32_t info1                 // header: info1 + info2
  uint32_t info2.
  struct {                           // content: sensor data stream format
    uint16_t x;
    uint16_t y;
    uint16_t z;
  } accelerometer [30];             // number of samples in one data stream record
}
```

```yml
sds:
  header:
    - value: info1
      type: uint32_t
    - value: info2
      type: uint32_t
  content:
    - value: x
      type: uint16_t
    - value: y
      type: uint16_t
    - value: z
      type: uint16_t
```
